import {test,expect} from '@playwright/test'
const origin='http://127.0.0.1:8787'
async function login(page){
  await page.goto('/admin/')
  await page.getByLabel('อีเมล',{exact:true}).fill('admin@example.test')
  await page.getByLabel('รหัสผ่าน',{exact:true}).fill('Natee-CI-only-passphrase-2026!')
  await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click()
  await expect(page.getByLabel('เบอร์โทรหลัก',{exact:true})).toBeVisible()
}
async function credentials(page){
  const session=await(await page.request.get('/api/session')).json()
  return {Origin:origin,'X-CSRF-Token':session.csrf}
}
test('admin sections, repeaters, SEO, brand, history and draft recovery',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await login(page)
  const original=await(await page.request.get('/api/content')).json()
  const nav=page.getByRole('navigation',{name:'เมนูหลังบ้าน'})
  for(const name of ['สถิติ','ข้อมูลร้าน','หน้าแรก','บริการ','ประเภทรถ','ราคา','ขั้นตอน','พื้นที่บริการ','ผลงาน','คำถามที่พบบ่อย','ข้อความและปุ่ม','ค้นหาและแชร์','แบบฟอร์มและรีวิว','ข้อความติดต่อ','คลังสื่อ','ประวัติ','ผู้ดูแล','บัญชีของฉัน']){
    await nav.getByRole('button',{name,exact:true}).click()
    await expect(page.getByRole('heading',{name,exact:true})).toBeVisible()
  }
  await nav.getByRole('button',{name:'บริการ',exact:true}).click()
  const rows=page.locator('.repeat-row'),count=await rows.count()
  await page.getByRole('button',{name:'+ เพิ่มรายการ',exact:true}).click()
  await expect(rows).toHaveCount(count+1)
  await rows.last().getByLabel('หัวข้อ',{exact:true}).fill('บริการทดสอบลำดับ')
  await page.getByRole('button',{name:'เลื่อนรายการ '+(count+1)+' ขึ้น',exact:true}).click()
  await expect(rows.nth(count-1).locator('.row-heading strong')).toHaveText('บริการทดสอบลำดับ')
  page.once('dialog',d=>d.accept())
  await rows.nth(count-1).getByRole('button',{name:'ลบรายการ',exact:true}).click()
  await expect(rows).toHaveCount(count)
  page.once('dialog',d=>d.accept())
  await page.getByRole('button',{name:'โหลดล่าสุด',exact:true}).click()
  await nav.getByRole('button',{name:'ค้นหาและแชร์',exact:true}).click()
  await page.getByLabel('หัวข้อ',{exact:true}).fill('SEO acceptance title for Natee')
  await page.getByLabel('คำอธิบายสำหรับผลค้นหา',{exact:true}).fill('An acceptance description for the customer website.')
  await page.getByRole('button',{name:'บันทึกและเผยแพร่เนื้อหา',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('บันทึกและเผยแพร่เนื้อหาแล้ว')
  expect(await(await page.request.get('/')).text()).toContain('<title>SEO acceptance title for Natee</title>')
  await nav.getByRole('button',{name:'ข้อมูลร้าน',exact:true}).click()
  await page.getByLabel('สีหลักเว็บไซต์',{exact:true}).fill('#ffffff')
  await page.getByRole('button',{name:'บันทึกและเผยแพร่เนื้อหา',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('สีหลักสว่างเกินไป')
  await page.getByLabel('สีหลักเว็บไซต์',{exact:true}).fill('#125a8a')
  await page.getByRole('button',{name:'บันทึกและเผยแพร่เนื้อหา',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('บันทึกและเผยแพร่เนื้อหาแล้ว')
  expect(await(await page.request.get('/')).text()).toContain('--natee-brand:#125a8a')
  await nav.getByRole('button',{name:'ประวัติ',exact:true}).click()
  await expect(page.getByRole('button',{name:'กู้คืนเป็นแบบร่าง',exact:true}).first()).toBeVisible()
  await page.getByRole('button',{name:'กู้คืนเป็นแบบร่าง',exact:true}).first().click()
  await expect(page.getByRole('status')).toContainText('กู้คืนเป็นแบบร่างแล้ว')
  page.once('dialog',d=>d.accept())
  await page.getByRole('button',{name:'โหลดล่าสุด',exact:true}).click()
  await nav.getByRole('button',{name:'หน้าแรก',exact:true}).click()
  await page.getByLabel('หัวข้อหน้าแรก',{exact:true}).fill('แบบร่างต้องอยู่หลังล็อกอินใหม่')
  const headers=await credentials(page)
  await page.request.post('/api/logout',{headers,data:{}})
  await page.getByRole('button',{name:'บันทึกและเผยแพร่เนื้อหา',exact:true}).click()
  await expect(page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true})).toBeVisible()
  await page.getByLabel('อีเมล',{exact:true}).fill('admin@example.test')
  await page.getByLabel('รหัสผ่าน',{exact:true}).fill('Natee-CI-only-passphrase-2026!')
  await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click()
  await expect(page.getByLabel('หัวข้อหน้าแรก',{exact:true})).toHaveValue('แบบร่างต้องอยู่หลังล็อกอินใหม่')
  await page.getByRole('button',{name:'บันทึกและเผยแพร่เนื้อหา',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('บันทึกและเผยแพร่เนื้อหาแล้ว')
  await nav.getByRole('button',{name:'ประวัติ',exact:true}).click()
  const downloaded=page.waitForEvent('download')
  await page.getByRole('button',{name:'ดาวน์โหลดข้อมูลเนื้อหา',exact:true}).click()
  expect((await downloaded).suggestedFilename()).toMatch(/^natee-content-v\d+\.json$/)
  const current=await(await page.request.get('/api/content')).json()
  expect((await page.request.put('/api/content',{headers:await credentials(page),data:{content:original.content,version:current.version}})).status()).toBe(200)
  expect(errors).toEqual([])
})
test('admin can add and disable an admin account from the UI',async({page})=>{
  await login(page)
  await page.getByRole('navigation',{name:'เมนูหลังบ้าน'}).getByRole('button',{name:'ผู้ดูแล',exact:true}).click()
  await page.getByLabel('อีเมลผู้ดูแล',{exact:true}).fill('ui-admin@example.test')
  await page.getByLabel('รหัสผ่านเริ่มต้น',{exact:true}).fill('UI-admin-CI-only-passphrase!')
  await page.getByRole('button',{name:'เพิ่มผู้ดูแล',exact:true}).click()
  const account=page.locator('.inquiry').filter({hasText:'ui-admin@example.test'})
  await expect(account).toBeVisible()
  page.once('dialog',d=>d.accept())
  await account.getByRole('button',{name:'ปิดใช้งาน',exact:true}).click()
  await expect(account.getByRole('button',{name:'เปิดใช้งาน',exact:true})).toBeVisible()
})
