import {test,expect} from '@playwright/test'
test('public website remains public; admin login and logout work',async({page})=>{
  await page.goto('/')
  await expect(page.locator('h1')).toBeVisible()
  await expect(page.locator('input[type=password]')).toHaveCount(0)
  await page.goto('/admin/')
  await page.getByLabel('อีเมล',{exact:true}).fill('admin@example.test')
  await page.getByLabel('รหัสผ่าน',{exact:true}).fill('wrong-password')
  await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('ไม่ถูกต้อง')
  await page.getByLabel('รหัสผ่าน',{exact:true}).fill('Natee-CI-only-passphrase-2026!')
  await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('เข้าสู่ระบบแล้ว')
  await page.reload()
  await expect(page.getByRole('status')).toContainText('เข้าสู่ระบบแล้ว')
  await page.screenshot({path:'test-results/admin-auth-desktop.png',fullPage:true})
  await page.setViewportSize({width:375,height:812})
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/admin-auth-mobile.png',fullPage:true})
  await page.getByRole('button',{name:'ออกจากระบบ',exact:true}).click()
  await expect(page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true})).toBeVisible()
})
