import {test,expect} from '@playwright/test'
test('admin edits both languages and published content survives a new page load',async({page})=>{
  await page.goto('/admin/')
  await page.getByLabel('อีเมล',{exact:true}).fill('admin@example.test')
  await page.getByLabel('รหัสผ่าน',{exact:true}).fill('Natee-CI-only-passphrase-2026!')
  await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click()
  await expect(page.getByRole('heading',{name:'ข้อมูลร้าน',exact:true})).toBeVisible()
  const original=await (await page.request.get('/api/content')).json()
  await page.getByRole('button',{name:'หน้าแรก',exact:true}).click()
  await page.getByLabel('หัวข้อหน้าแรก',{exact:true}).fill('แก้ไขผ่านแอดมินเพื่อทดสอบ')
  await page.getByRole('button',{name:'English',exact:true}).click()
  await page.getByLabel('หัวข้อหน้าแรก',{exact:true}).fill('Edited in the admin acceptance test')
  await page.getByRole('button',{name:'บันทึกและเผยแพร่เนื้อหา',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('บันทึกและเผยแพร่เนื้อหาแล้ว')
  const publicPage=await page.context().newPage()
  await publicPage.goto('/')
  await expect(publicPage.locator('h1')).toHaveText('แก้ไขผ่านแอดมินเพื่อทดสอบ')
  await publicPage.goto('/en.html')
  await expect(publicPage.locator('h1')).toHaveText('Edited in the admin acceptance test')
  await page.screenshot({path:'test-results/admin-content-desktop.png',fullPage:true})
  await page.setViewportSize({width:375,height:812})
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/admin-content-mobile.png',fullPage:true})
  const session=await (await page.request.get('/api/session')).json()
  const current=await (await page.request.get('/api/content')).json()
  const restored=await page.request.put('/api/content',{headers:{Origin:'http://127.0.0.1:8787','X-CSRF-Token':session.csrf},data:{content:original.content,version:current.version}})
  expect(restored.status()).toBe(200)
})
