import {test,expect} from '@playwright/test'
test('public form submits to the admin inbox; media upload appears in the library',async({page})=>{
  await page.goto('/')
  await page.getByLabel('ชื่อผู้ติดต่อ').fill('Browser enquiry')
  await page.getByLabel('เบอร์โทรกลับ').fill('0812345678')
  await page.getByLabel('พื้นที่จัดส่ง',{exact:true}).fill('เชียงใหม่')
  await page.getByRole('button',{name:'ส่งข้อมูลให้ทีมงานติดต่อกลับ',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('ส่งข้อความเรียบร้อยแล้ว')
  await page.goto('/admin/')
  await page.getByLabel('อีเมล',{exact:true}).fill('admin@example.test')
  await page.getByLabel('รหัสผ่าน',{exact:true}).fill('Natee-CI-only-passphrase-2026!')
  await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click()
  await expect(page.getByRole('heading',{name:'ข้อมูลร้าน',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'ข้อความติดต่อ',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Browser enquiry',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'ทำเครื่องหมายว่าอ่านแล้ว'}).first().click()
  await expect(page.locator('.badge').first()).toHaveText('อ่านแล้ว')
  await page.getByRole('button',{name:'คลังสื่อ',exact:true}).click()
  const catalog=await (await page.request.get('/api/media')).json()
  const count=catalog.length
  await expect(page.locator('.media-grid article')).toHaveCount(count)
  await page.getByLabel('เพิ่มไฟล์',{exact:true}).setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jN1kAAAAASUVORK5CYII=','base64')})
  await expect(page.locator('.media-grid article')).toHaveCount(count+1)
  await expect(page.getByRole('status')).toContainText('อัปโหลดแล้ว')
  await page.screenshot({path:'test-results/admin-media.png',fullPage:true})
})
