/**
 * ข้อมูลตั้งต้นของเว็บไซต์ หลังติดตั้งแก้และบันทึกผ่านแอดมินลง D1
 * ทุกข้อความต้องมีคู่ภาษาไทยและอังกฤษ ตรวจความครบก่อนส่งมอบ
 */

export const CONTACT = {
  phone: '064-825-3515',
  phoneHref: 'tel:0648253515',
  phone2: '082-642-7079',
  phone2Href: 'tel:0826427079',
  lineId: 'tnwater',
  lineUrl: 'https://line.me/ti/p/vTy9Ug5mTd',
  facebookUrl: 'https://www.facebook.com/TNWATER99',
  email: 'TNWater99@gmail.com',
  mapUrl: 'https://www.google.com/maps/dir/?api=1&destination=' +
    encodeURIComponent('100/29 หมู่ 3 ตำบลสันผีเสื้อ อำเภอเมืองเชียงใหม่ เชียงใหม่ 50300'),
  mapEmbed: 'https://www.google.com/maps?q=' +
    encodeURIComponent('100/29 หมู่ 3 ตำบลสันผีเสื้อ อำเภอเมืองเชียงใหม่ เชียงใหม่ 50300') +
    '&hl=th&z=15&output=embed',
}

/** ฟอร์มส่งเข้า D1 ผ่าน Worker; เปิด/ปิดในแอดมิน ไม่มี external API key */
export const FORM = {
  enabled: true,
  accessKey: '',
  endpoint: 'api/inquiries',
}
export const ASSETS = {
  logo: 'logo', hero: 'truck-6wheel', about: 'work-11', qr: 'line-qr', share: 'og-banner',
}


/**
 * คะแนนรีวิวจาก Google Business Profile
 *
 * ใส่ค่าจริงเท่านั้น ห้ามใส่ตัวเลขที่ไม่มีอยู่จริง
 * ถ้า count เป็นศูนย์ ส่วนนี้จะไม่ถูกแสดงและไม่ถูกส่งให้ Google
 */
// ค่าจริงจากโปรไฟล์ร้านบน Google Maps เมื่อ 3 ต.ค. 2569 เจ้าของร้านอัปเดตได้ในหลังบ้านเมื่อมีรีวิวเพิ่ม
export const REVIEWS = {
  rating: 5,
  count: 5,
  url: 'https://search.google.com/local/reviews?placeid=ChIJr0B_fAA72jARczGvRfNdzx4',
}

export const BRAND = { color: '#0f6fbf' }
export const SEO = {
  th: { title: 'รถน้ำเชียงใหม่ รถส่งน้ำประปา 24 ชม. เชียงใหม่ ลำพูน | ธารนที', description: 'ธารนที รถส่งน้ำ รถขายน้ำประปาเชียงใหม่ ลำพูน 24 ชั่วโมง เติมน้ำแท็งก์ เติมสระว่ายน้ำ ล้างถนน รดน้ำต้นไม้ สนามหญ้า รถน้ำงานสงกรานต์' },
  en: { title: 'Water Truck Chiang Mai, 24 Hour Water Delivery | Natee', description: 'Natee water truck service in Chiang Mai and Lamphun, 24 hours. Tank filling, swimming pools, road washing, lawn watering, Songkran and events.' },
}

export const GALLERY = [
  'work-01', 'work-02', 'work-03', 'work-04', 'work-05', 'work-06',
  'work-07', 'work-08', 'work-09', 'work-10', 'work-11', 'work-12',
]

export const I18N = {
  th: {
    lang: 'th',
    siteName: 'ธารนที',
    tagline: 'รถส่งน้ำประปาเชียงใหม่ บริการ 24 ชั่วโมง',
    address: '100/29 หมู่ 3 ตำบลสันผีเสื้อ อำเภอเมืองเชียงใหม่ จังหวัดเชียงใหม่ 50300',
    hours: 'ให้บริการทุกวัน ตลอด 24 ชั่วโมง',

    nav: {
      services: 'บริการ',
      fleet: 'ประเภทรถ',
      pricing: 'ราคา',
      areas: 'พื้นที่ให้บริการ',
      gallery: 'ผลงาน',
      faq: 'คำถามที่พบบ่อย',
      contact: 'ติดต่อเรา',
    },

    skipToContent: 'ข้ามไปยังเนื้อหาหลัก',
    openMenu: 'เปิดเมนู',
    closeMenu: 'ปิดเมนู',
    mainMenu: 'เมนูหลัก',
    changeLanguage: 'เปลี่ยนภาษา',
    callLabel: 'โทรสั่งน้ำ',
    callHeader: 'โทรสั่งน้ำ 24 ชม.',
    lineLabel: 'ทักไลน์',
    orCall: 'หรือโทร',

    heroEyebrow: 'ส่งด่วน ส่งไว ใส่ใจบริการ',
    heroTitle: 'รถส่งน้ำประปา เชียงใหม่ ลำพูน ราคาถูก บริการ 24 ชั่วโมง',
    heroSubtitle: 'รถส่งน้ำ รถขายน้ำประปาสะอาด เติมแท็งก์น้ำ เติมสระว่ายน้ำ ล้างถนน งานก่อสร้าง รดน้ำต้นไม้และสนามหญ้า รวมถึงงานอีเวนต์และงานสงกรานต์ ส่งตรงถึงหน้างานทุกพื้นที่ในเชียงใหม่และลำพูน',
    heroNote: 'แจ้งปริมาณน้ำ สถานที่ และเวลาที่ต้องการ ทีมงานประเมินราคาให้ทันที',

    highlightsTitle: 'จุดเด่นของบริการ',
    highlights: [
      { icon: 'clock', title: 'เน้นความรวดเร็ว', text: 'เราเข้าใจดีว่าน้ำคือสิ่งจำเป็น เมื่อลูกค้าโทรสั่ง เราพร้อมประสานงานและออกรถทันที' },
      { icon: 'check', title: 'ตรงต่อเวลา', text: 'หมดกังวลเรื่องเวลานัดหมาย เราไปถึงหน้างานตรงตามเวลาที่ตกลงไว้' },
      { icon: 'drop', title: 'น้ำประปาสำหรับงานอุปโภค', text: 'บริการส่งน้ำประปาสำหรับเติมแท็งก์และงานอุปโภค กรุณาแจ้งลักษณะการใช้งานเพื่อสอบถามรายละเอียดก่อนสั่ง' },
      { icon: 'truck', title: 'เข้าได้ทุกพื้นที่', text: 'มีทั้งรถ 4 ล้อ และ 6 ล้อ จึงส่งน้ำได้ทุกพื้นที่ในเชียงใหม่ ลำพูน และจังหวัดใกล้เคียง' },
    ],

    aboutTitle: 'เรื่องน้ำประปาและความสะอาด ไว้ใจให้ ธารนที ดูแล',
    aboutText: 'ธารนที รถน้ำประปาเชียงใหม่ เกิดขึ้นจากความตั้งใจที่จะให้บริการน้ำประปาสะอาดและมีคุณภาพแก่ประชาชนในจังหวัดเชียงใหม่และลำพูน ทั้งบ้านพักอาศัย ร้านค้า สถานประกอบการ งานก่อสร้าง พื้นที่ที่ต้องการน้ำสำรองในช่วงน้ำประปาไม่เพียงพอ รวมถึงการเติมสระว่ายน้ำ งานกิจกรรมพิเศษ และพื้นที่ห่างไกลที่ระบบท่อส่งน้ำยังเข้าไม่ถึง เราให้บริการด้วยความใส่ใจ รับผิดชอบ และมีมาตรฐาน',
    aboutQuote: 'น้ำคือชีวิต หากไม่มีน้ำ คนอยู่ไม่ได้',

    servicesTitle: 'บริการของเรา',
    servicesSubtitle: 'รถส่งน้ำเชียงใหม่ รับส่งน้ำประปาทุกประเภทงาน ทั้งงานเร่งด่วนและงานประจำ ตลอด 24 ชั่วโมง',
    services: [
      { icon: 'tank', title: 'เติมน้ำลงแท็งก์เก็บน้ำ', text: 'น้ำไม่ไหล ท่อประปาแตก หรือน้ำประปาเข้าไม่ถึง สั่งซื้อน้ำแล้วรถเติมน้ำใส่แท็งก์ให้ใช้ได้ทันที ทั้งบ้านพัก หอพัก คอนโด และอาคารสำนักงาน' },
      { icon: 'pool', title: 'เติมสระว่ายน้ำ', text: 'เติมสระว่ายน้ำบ้าน โรงแรม รีสอร์ท คอนโด บ่อน้ำพุ และบ่อเลี้ยงปลา ด้วยน้ำประปาสะอาดมีมาตรฐาน' },
      { icon: 'build', title: 'ไซต์งานก่อสร้าง', text: 'ส่งน้ำเป็นเที่ยวหรือรายวันสำหรับงานก่อสร้าง ผสมปูน บดอัดดิน และน้ำใช้ในแคมป์คนงาน' },
      { icon: 'leaf', title: 'รดน้ำต้นไม้และสนามหญ้า', text: 'รดน้ำต้นไม้ รดน้ำสนามหญ้า สวน ต้นไม้ในโครงการและพื้นที่เกษตร โดยเฉพาะช่วงหน้าแล้งที่น้ำไม่เพียงพอ' },
      { icon: 'road', title: 'รถฉีดน้ำ ล้างถนนและอาคาร', text: 'ฉีดล้างถนน ลานจอดรถ อาคาร และพื้นที่หน้างานที่มีฝุ่นดินโคลน ให้กลับมาสะอาดพร้อมใช้' },
      { icon: 'event', title: 'รถน้ำงานสงกรานต์และงานอีเวนต์', text: 'รถน้ำสำหรับงานสงกรานต์ งานคอนเสิร์ต งานอีเวนต์ และงานเทศกาล จัดน้ำสำรองและวางแผนรอบส่งล่วงหน้าได้' },
      { icon: 'factory', title: 'โรงงานอุตสาหกรรม', text: 'รองรับการใช้น้ำปริมาณมากในโรงงานและสถานประกอบการ ส่งได้ต่อเนื่องตามรอบที่ตกลงกัน' },
      { icon: 'hotel', title: 'โรงแรม ร้านอาหาร และคาเฟ่', text: 'ส่งน้ำประจำวันให้ธุรกิจบริการ ไม่ให้ขาดน้ำระหว่างเปิดร้าน วางแผนรอบส่งล่วงหน้าได้' },
    ],

    fleetTitle: 'รถบรรทุกน้ำ 4 ล้อ และ 6 ล้อ',
    fleetSubtitle: 'รถบรรทุกน้ำเชียงใหม่ของธารนทีมีทั้ง 4 ล้อและ 6 ล้อ เลือกขนาดรถให้เหมาะกับปริมาณน้ำและเส้นทางเข้าออกของหน้างาน',
    fleet: [
      { image: 'truck-6wheel', name: 'รถส่งน้ำ 6 ล้อ', capacity: 'ขนาดใหญ่ จุใจ', text: 'เหมาะสำหรับโรงงานอุตสาหกรรม คอนโดมิเนียม สระว่ายน้ำ โรงแรม หรือโครงการก่อสร้างที่ต้องใช้น้ำปริมาณมาก คุ้มค่า ประหยัดเวลา' },
      { image: 'truck-4wheel', name: 'รถส่งน้ำ 4 ล้อ', capacity: 'ขนาดกะทัดรัด เข้าซอยแคบได้', text: 'เหมาะสำหรับบ้านพักอาศัย ทาวน์โฮม หรือไซต์งานที่อยู่ในซอยแคบที่รถใหญ่เข้าไม่ได้ เข้าถึงง่าย จอดสะดวก ไม่กีดขวางการจราจร' },
    ],

    pricingTitle: 'อัตราค่าบริการ',
    pricingSubtitle: 'ขายน้ำประปาเชียงใหม่ ราคาขึ้นอยู่กับปริมาณน้ำ ระยะทาง และช่วงเวลาที่จัดส่ง โทรสอบถามเพื่อรับราคาที่แน่นอน',
    pricing: [
      {
        name: 'รถส่งน้ำ 4 ล้อ',
        detail: 'เหมาะกับบ้านพักอาศัยและซอยแคบ',
        price: 'สอบถามราคา',
        includes: ['เข้าซอยแคบและที่จอดจำกัดได้', 'เหมาะกับการเติมแท็งก์บ้านและหอพัก', 'แจ้งราคาก่อนออกรถทุกครั้ง'],
      },
      {
        name: 'รถส่งน้ำ 6 ล้อ',
        detail: 'เหมาะกับไซต์งาน โรงงาน และสระว่ายน้ำ',
        price: 'สอบถามราคา',
        includes: ['ส่งน้ำปริมาณมากได้ในรอบเดียว', 'เหมาะกับไซต์ก่อสร้าง โรงงาน และการเติมสระว่ายน้ำ', 'วางแผนรอบส่งล่วงหน้าได้'],
      },
      {
        name: 'ส่งประจำรายเดือน',
        detail: 'วางรอบส่งล่วงหน้า มีราคาพิเศษ',
        price: 'สอบถามราคา',
        includes: ['กำหนดวันและเวลาส่งประจำได้', 'มีราคาพิเศษสำหรับลูกค้าประจำ', 'รองรับการวางบิลสำหรับลูกค้าองค์กร'],
      },
    ],
    pricingNote: 'ราคาข้างต้นเป็นราคาเริ่มต้น พื้นที่นอกเขตอำเภอเมืองและงานเร่งด่วนนอกเวลาอาจมีค่าบริการเพิ่ม แจ้งราคาให้ทราบก่อนออกรถทุกครั้ง',
    priceCallNow: 'โทรสอบถามราคา',

    stepsTitle: 'สั่งน้ำง่ายใน 3 ขั้นตอน',
    steps: [
      { title: 'โทรหรือทักไลน์', text: 'แจ้งปริมาณน้ำที่ต้องการ สถานที่จัดส่ง และเวลาที่สะดวกรับน้ำ' },
      { title: 'รับราคาและยืนยัน', text: 'ทีมงานประเมินระยะทางและแจ้งราคาให้ทราบทันที ยืนยันแล้วจัดคิวรถให้' },
      { title: 'รถออกและส่งถึงที่', text: 'พนักงานเติมน้ำให้ถึงจุดที่ต้องการ ตรวจสอบปริมาณร่วมกันก่อนชำระเงิน' },
    ],

    areasTitle: 'พื้นที่ให้บริการ',
    areasSubtitle: 'ให้บริการทั่วจังหวัดเชียงใหม่และจังหวัดลำพูน รวมถึงพื้นที่ใกล้เคียง กำลังหารถน้ำใกล้ฉัน ส่งพิกัดหน้างานมาได้เลย พื้นที่นอกเหนือจากนี้สอบถามเพิ่มเติมได้',
    areas: [
      'อำเภอเมืองเชียงใหม่', 'อำเภอสันทราย', 'อำเภอสารภี', 'อำเภอหางดง',
      'อำเภอสันกำแพง', 'อำเภอดอยสะเก็ด', 'อำเภอแม่ริม', 'จังหวัดลำพูน',
      'อำเภอสันป่าตอง', 'อำเภอแม่แตง', 'อำเภอสะเมิง', 'อำเภอจอมทอง', 'อำเภอแม่ออน',
    ],

    servicePages: [
      {
        slug: 'tank-filling',
        icon: 'tank',
        navLabel: 'เติมน้ำแท็งก์ ซื้อน้ำ',
        metaTitle: 'รถเติมน้ำ ซื้อน้ำเชียงใหม่ ส่งน้ำเติมแท็งก์ 24 ชม. | ธารนที',
        metaDescription: 'น้ำไม่ไหล ท่อแตก น้ำประปาไม่พอ สั่งซื้อน้ำกับรถเติมน้ำธารนที ส่งน้ำประปาเติมแท็งก์ถึงบ้าน หอพัก คอนโด ร้านค้า ทั่วเชียงใหม่และลำพูน',
        eyebrow: 'บริการเติมน้ำ',
        title: 'รถเติมน้ำ ซื้อน้ำเติมแท็งก์ เชียงใหม่',
        subtitle: 'น้ำไม่ไหล ท่อประปาแตก หรือน้ำประปาไม่พอใช้ สั่งรถขายน้ำเชียงใหม่ ธารนที มาเติมแท็งก์ให้ใช้ได้ทันที',
        image: 'work-05',
        imageAlt: 'แท็งก์เก็บน้ำสีน้ำเงินกำลังถูกเติมน้ำจากสายส่งน้ำของธารนที',
        imageCaption: 'เติมน้ำลงแท็งก์เก็บน้ำของลูกค้า',
        intro: 'เวลาน้ำประปาหยุดไหล ท่อแตก หรือแรงดันน้ำไม่พอ ทั้งบ้านก็ใช้ชีวิตลำบาก ธารนทีมีรถส่งน้ำและรถขายน้ำประปาพร้อมออกงานตลอด 24 ชั่วโมง เติมน้ำลงแท็งก์หรือถังเก็บน้ำให้ใช้ต่อได้ทันที ทั้งบ้านพัก หอพัก คอนโด อาคารสำนักงาน และร้านค้าทั่วเชียงใหม่และลำพูน',
        fitTitle: 'เหมาะกับงานแบบไหน',
        fits: ['บ้านที่น้ำประปาไม่ไหลหรือไหลอ่อนช่วงหน้าแล้ง', 'หอพัก คอนโด และอพาร์ตเมนต์ที่ต้องเติมแท็งก์ส่วนกลาง', 'ร้านค้า ร้านอาหาร และคาเฟ่ที่ขาดน้ำระหว่างเปิดร้าน', 'บ้านหรือที่ดินที่ระบบท่อประปายังเข้าไม่ถึง', 'งานซ่อมท่อที่ต้องปิดน้ำหลายชั่วโมง'],
        tipsTitle: 'ข้อแนะนำก่อนสั่งซื้อน้ำ',
        tips: ['ดูขนาดแท็งก์หรือปริมาณน้ำที่ต้องการ แล้วแจ้งตอนโทรสั่ง', 'บอกลักษณะทางเข้า ถ้าซอยแคบทีมงานจะส่งรถ 4 ล้อไปแทน', 'ส่งพิกัดหน้างานทางไลน์ ให้รถไปถึงได้ไม่หลง', 'น้ำที่ส่งเป็นน้ำประปาสำหรับงานอุปโภค ไม่ได้จำหน่ายเป็นน้ำดื่ม'],
        faq: [
          { q: 'ซื้อน้ำเติมแท็งก์ คิดราคาอย่างไร', a: 'คิดตามปริมาณน้ำและระยะทางจากจุดรับน้ำถึงหน้างาน ทีมงานแจ้งราคาทั้งหมดก่อนออกรถ ไม่มีค่าใช้จ่ายเพิ่มหน้างาน' },
          { q: 'สั่งรถเติมน้ำตอนกลางคืนได้ไหม', a: 'ได้ ธารนทีรับงานตลอด 24 ชั่วโมงทุกวัน โทรหรือทักไลน์ได้ทุกเวลา' },
          { q: 'น้ำที่เติมแท็งก์ใช้ดื่มได้ไหม', a: 'เป็นน้ำประปาสำหรับงานอุปโภค เช่น อาบน้ำ ซักล้าง ชำระล้าง ไม่ได้จำหน่ายเป็นน้ำดื่ม' },
        ],
      },
      {
        slug: 'pool-filling',
        icon: 'pool',
        navLabel: 'เติมสระว่ายน้ำ',
        metaTitle: 'รถน้ำเติมสระว่ายน้ำ เชียงใหม่ ลำพูน บ้าน โรงแรม รีสอร์ท | ธารนที',
        metaDescription: 'รถส่งน้ำประปาเติมสระว่ายน้ำ บ่อน้ำพุ และบ่อเลี้ยงปลา สำหรับบ้าน โรงแรม รีสอร์ท และคอนโด ทั่วเชียงใหม่และลำพูน แจ้งขนาดสระเพื่อประเมินจำนวนเที่ยว',
        eyebrow: 'บริการเติมสระ',
        title: 'รถน้ำเติมสระว่ายน้ำ เชียงใหม่',
        subtitle: 'เติมสระใหม่ เปลี่ยนน้ำสระ หรือเติมน้ำที่ระเหยไปช่วงหน้าร้อน ส่งน้ำประปาถึงขอบสระ',
        image: 'work-11',
        imageAlt: 'รถส่งน้ำธารนทีต่อสายส่งน้ำเข้าบ้านพักที่หน้างาน',
        imageCaption: 'ต่อสายส่งน้ำจากรถเข้าพื้นที่บ้านพัก',
        intro: 'การเติมสระว่ายน้ำด้วยน้ำจากก๊อกในบ้านใช้เวลานานและกระทบน้ำใช้ในบ้าน ธารนทีส่งน้ำประปาด้วยรถส่งน้ำ ต่อสายเติมลงสระได้โดยตรง เหมาะทั้งสระในบ้าน โรงแรม รีสอร์ท คอนโด รวมถึงบ่อน้ำพุและบ่อเลี้ยงปลา ทั่วเชียงใหม่และลำพูน',
        fitTitle: 'เหมาะกับงานแบบไหน',
        fits: ['สระว่ายน้ำที่เพิ่งสร้างเสร็จและต้องเติมครั้งแรก', 'สระที่ถ่ายน้ำออกเพื่อทำความสะอาดหรือซ่อม', 'สระโรงแรมและรีสอร์ทที่ต้องการน้ำเพิ่มช่วงหน้าร้อน', 'บ่อน้ำพุ บ่อปลา และบ่อแต่งสวน'],
        tipsTitle: 'ข้อแนะนำก่อนสั่งเติมสระ',
        tips: ['แจ้งขนาดสระ กว้าง ยาว และความลึกโดยประมาณ ทีมงานจะคำนวณจำนวนเที่ยวรถให้', 'บอกระยะจากที่จอดรถถึงขอบสระ เพื่อเตรียมสายส่งน้ำให้ยาวพอ', 'ถ้าต้องการให้เสร็จในวันเดียว แจ้งล่วงหน้าเพื่อจัดคิวรถหลายเที่ยวต่อเนื่อง'],
        faq: [
          { q: 'เติมสระว่ายน้ำต้องใช้รถกี่เที่ยว', a: 'ขึ้นอยู่กับขนาดสระและขนาดรถ แจ้งกว้าง ยาว และความลึกของสระ ทีมงานจะคำนวณปริมาณน้ำและจำนวนเที่ยวให้ก่อนยืนยันราคา' },
          { q: 'รถเข้าไม่ถึงขอบสระทำอย่างไร', a: 'ทีมงานต่อสายส่งน้ำจากรถไปถึงสระได้ แจ้งระยะทางตอนสั่งเพื่อเตรียมสายให้พอ' },
          { q: 'รับเติมบ่อปลาหรือบ่อน้ำพุไหม', a: 'รับ ใช้น้ำประปาเหมือนงานเติมสระ แจ้งขนาดบ่อเพื่อประเมินปริมาณน้ำ' },
        ],
      },
      {
        slug: 'songkran',
        icon: 'event',
        navLabel: 'รถน้ำสงกรานต์และงานอีเวนต์',
        metaTitle: 'รถน้ำสงกรานต์ เชียงใหม่ รถน้ำงานอีเวนต์ งานเทศกาล | ธารนที',
        metaDescription: 'จองรถน้ำสำหรับงานสงกรานต์ งานวัด งานเทศกาล คอนเสิร์ต และงานอีเวนต์ในเชียงใหม่และลำพูน วางแผนรอบส่งน้ำล่วงหน้า ส่งน้ำถึงจุดงานตามเวลา',
        eyebrow: 'บริการงานเทศกาล',
        title: 'รถน้ำสงกรานต์และงานอีเวนต์ เชียงใหม่',
        subtitle: 'น้ำสำรองสำหรับงานสงกรานต์ งานวัด คอนเสิร์ต และงานเทศกาล จองล่วงหน้าเพื่อให้ได้คิวรถตรงเวลา',
        image: 'work-01',
        imageAlt: 'รถส่งน้ำธารนทีจอดให้บริการในงานเทศกาลยามค่ำคืน',
        imageCaption: 'ส่งน้ำให้งานเทศกาลยามค่ำคืน',
        intro: 'งานสงกรานต์และงานเทศกาลใช้น้ำปริมาณมากในเวลาสั้น ถ้าน้ำหมดกลางงานก็กระทบทั้งผู้จัดและผู้มาร่วมงาน ธารนทีรับจัดรถน้ำสำหรับงานสงกรานต์ งานวัด งานคอนเสิร์ต และงานอีเวนต์ วางแผนรอบส่งน้ำร่วมกับผู้จัดงานตั้งแต่ก่อนวันงาน',
        fitTitle: 'เหมาะกับงานแบบไหน',
        fits: ['งานสงกรานต์ของชุมชน หมู่บ้าน ร้านค้า และองค์กร', 'งานวัด งานประเพณี และงานเทศกาลประจำปี', 'คอนเสิร์ต งานอีเวนต์ และงานออกร้านที่ต้องใช้น้ำสำรอง', 'จุดเติมน้ำสำหรับถังหรือแท็งก์ที่ตั้งไว้ในงาน'],
        tipsTitle: 'ข้อแนะนำก่อนจองรถน้ำ',
        tips: ['จองล่วงหน้าเพื่อจัดคิวรถให้ตรงวันและเวลางาน', 'แจ้งวัน เวลา และจำนวนรอบที่ต้องการให้เติมน้ำระหว่างงาน', 'ส่งแผนผังหรือพิกัดจุดจอดรถในงาน ให้รถเข้าออกได้สะดวก'],
        faq: [
          { q: 'ต้องจองรถน้ำสงกรานต์ล่วงหน้ากี่วัน', a: 'ยิ่งเร็วยิ่งดี โดยเฉพาะช่วงสงกรานต์ที่มีงานพร้อมกันหลายที่ โทรหรือทักไลน์แจ้งวันงานเพื่อจองคิวรถได้เลย' },
          { q: 'เติมน้ำหลายรอบระหว่างงานได้ไหม', a: 'ได้ วางแผนรอบส่งน้ำร่วมกันล่วงหน้า แจ้งช่วงเวลาที่ต้องการให้เติมน้ำแต่ละรอบ' },
          { q: 'รับงานนอกอำเภอเมืองไหม', a: 'รับทั่วเชียงใหม่และลำพูน พื้นที่อื่นสอบถามเพื่อประเมินระยะทางและราคาได้' },
        ],
      },
      {
        slug: 'road-washing',
        icon: 'road',
        navLabel: 'รถฉีดน้ำ ล้างถนน',
        metaTitle: 'รถฉีดน้ำ ล้างถนน ล้างลานจอดรถ เชียงใหม่ ลำพูน | ธารนที',
        metaDescription: 'รถฉีดน้ำล้างถนน ลานจอดรถ อาคาร และพื้นที่ที่มีฝุ่นดินโคลน หลังงานก่อสร้างหรือหลังน้ำท่วม ทั่วเชียงใหม่และลำพูน รับงานตลอด 24 ชั่วโมง',
        eyebrow: 'บริการล้างพื้นที่',
        title: 'รถฉีดน้ำล้างถนนและอาคาร เชียงใหม่',
        subtitle: 'ฉีดล้างถนน ลานจอดรถ และพื้นที่ที่มีฝุ่นดินโคลน ให้กลับมาสะอาดพร้อมใช้',
        image: 'work-06',
        imageAlt: 'ทีมงานธารนทีใช้สายน้ำฉีดล้างถนนในเวลากลางคืน',
        imageCaption: 'ฉีดล้างถนนในเวลากลางคืน',
        intro: 'ถนนหน้าโครงการ ลานจอดรถ หรือพื้นที่หลังงานก่อสร้างมักมีฝุ่นและดินโคลนสะสม ธารนทีมีรถส่งน้ำพร้อมสายฉีดน้ำสำหรับล้างพื้นที่ รับงานได้ทั้งกลางวันและกลางคืน ให้พื้นที่กลับมาสะอาดและใช้งานได้',
        fitTitle: 'เหมาะกับงานแบบไหน',
        fits: ['ถนนหน้าไซต์งานก่อสร้างที่มีดินโคลนติดล้อรถ', 'ลานจอดรถ ลานกิจกรรม และพื้นที่หน้าอาคาร', 'พื้นที่หลังน้ำท่วมที่มีโคลนตกค้าง', 'ล้างพื้นที่ก่อนหรือหลังจัดงานอีเวนต์'],
        tipsTitle: 'ข้อแนะนำก่อนสั่งล้างพื้นที่',
        tips: ['แจ้งขนาดพื้นที่และลักษณะความสกปรก เพื่อประเมินปริมาณน้ำ', 'ถ้าเป็นถนนสาธารณะ เลือกช่วงเวลาที่ไม่กระทบการจราจร', 'บอกจุดระบายน้ำในพื้นที่ ให้น้ำที่ฉีดล้างไหลออกได้'],
        faq: [
          { q: 'ล้างถนนตอนกลางคืนได้ไหม', a: 'ได้ ธารนทีรับงานตลอด 24 ชั่วโมง งานล้างถนนบางแห่งเหมาะกับช่วงกลางคืนที่รถน้อย' },
          { q: 'คิดค่าบริการล้างถนนอย่างไร', a: 'คิดตามปริมาณน้ำที่ใช้และระยะทางถึงหน้างาน แจ้งขนาดพื้นที่ ทีมงานจะประเมินและแจ้งราคาก่อนออกรถ' },
          { q: 'รับล้างพื้นอาคารหรือโกดังไหม', a: 'รับ แจ้งขนาดพื้นที่และจุดระบายน้ำ ทีมงานจะประเมินงานให้ก่อน' },
        ],
      },
      {
        slug: 'garden-watering',
        icon: 'leaf',
        navLabel: 'รดน้ำต้นไม้ สนามหญ้า',
        metaTitle: 'รถรดน้ำต้นไม้ รดน้ำสนามหญ้า เชียงใหม่ ช่วงหน้าแล้ง | ธารนที',
        metaDescription: 'รถน้ำรดน้ำต้นไม้ สนามหญ้า สวน ต้นไม้ในโครงการหมู่บ้าน และพื้นที่เกษตร ช่วงหน้าแล้งที่น้ำไม่พอ ทั่วเชียงใหม่และลำพูน รับงานรายครั้งหรือตามรอบ',
        eyebrow: 'บริการรดน้ำ',
        title: 'รถรดน้ำต้นไม้และสนามหญ้า เชียงใหม่',
        subtitle: 'ส่งน้ำรดสวน สนามหญ้า และต้นไม้ในโครงการ ช่วงหน้าแล้งที่น้ำไม่เพียงพอ',
        image: 'work-09',
        imageAlt: 'รถส่งน้ำธารนทีจอดส่งน้ำข้างแนวต้นไม้',
        imageCaption: 'ส่งน้ำให้พื้นที่ที่มีต้นไม้ของลูกค้า',
        intro: 'ช่วงหน้าแล้งในเชียงใหม่ น้ำที่มีอาจไม่พอสำหรับรดต้นไม้และสนามหญ้าพื้นที่กว้าง ธารนทีส่งน้ำประปาด้วยรถส่งน้ำสำหรับรดน้ำสวน สนามหญ้า ต้นไม้ในโครงการหมู่บ้าน รีสอร์ท และพื้นที่เกษตร รับทั้งงานรายครั้งและงานตามรอบที่ตกลงกัน',
        fitTitle: 'เหมาะกับงานแบบไหน',
        fits: ['สนามหญ้าและสวนในบ้าน รีสอร์ท และโรงแรม', 'ต้นไม้ในโครงการหมู่บ้านจัดสรรและพื้นที่ส่วนกลาง', 'ต้นไม้ที่เพิ่งปลูกใหม่ในโครงการก่อสร้าง', 'แปลงเกษตรและสวนผลไม้ช่วงที่ขาดน้ำ'],
        tipsTitle: 'ข้อแนะนำก่อนสั่งรดน้ำ',
        tips: ['แจ้งขนาดพื้นที่และจำนวนครั้งต่อสัปดาห์ที่ต้องการ', 'ถ้าต้องการรดตามรอบประจำ ตกลงวันและเวลากับทีมงานล่วงหน้า', 'บอกจุดที่รถจอดได้และระยะถึงพื้นที่รดน้ำ'],
        faq: [
          { q: 'รับรดน้ำต้นไม้เป็นประจำทุกสัปดาห์ไหม', a: 'รับ ตกลงรอบส่งน้ำล่วงหน้าได้ เหมาะกับช่วงหน้าแล้งที่ต้องรดต่อเนื่อง' },
          { q: 'รดน้ำสนามหญ้าใช้น้ำมากแค่ไหน', a: 'ขึ้นอยู่กับขนาดพื้นที่และสภาพอากาศ แจ้งขนาดสนาม ทีมงานจะช่วยประเมินปริมาณน้ำให้' },
          { q: 'ใช้น้ำอะไรรดต้นไม้', a: 'ใช้น้ำประปา ส่งจากรถส่งน้ำของธารนทีโดยตรง' },
        ],
      },
    ],
    serviceMore: 'ดูรายละเอียดบริการ',
    serviceRelated: 'บริการอื่นของธารนที',
    serviceFaqTitle: 'คำถามเกี่ยวกับบริการนี้',
    serviceBack: 'กลับหน้าแรก',

    knowledge: {
      navLabel: 'ความรู้',
      metaTitle: 'ความสำคัญของน้ำและน้ำประปา น้ำคือชีวิต | ธารนที',
      metaDescription: 'ความรู้เรื่องน้ำและน้ำประปา ความสำคัญต่อชีวิต การเกษตร ปศุสัตว์ อุตสาหกรรม และชุมชน จากทีมรถส่งน้ำประปาเชียงใหม่ ธารนที',
      eyebrow: 'บทความน่ารู้',
      title: 'น้ำคือชีวิต ความสำคัญของน้ำและน้ำประปา',
      subtitle: 'เรื่องที่ควรรู้เกี่ยวกับน้ำและระบบน้ำประปา ตั้งแต่การดำรงชีวิตประจำวัน ไปจนถึงการเกษตร ปศุสัตว์ อุตสาหกรรม และการกระจายน้ำให้ทั่วถึงทั้งชุมชน',
      quote: 'น้ำคือชีวิต หากไม่มีน้ำ คนอยู่ไม่ได้',
      quoteBy: 'พระราชดำรัส พระบาทสมเด็จพระบรมชนกาธิเบศร มหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร',
      intro: 'น้ำคือปัจจัยพื้นฐานที่สำคัญที่สุดของสิ่งมีชีวิตทุกชนิดบนโลก มนุษย์ขาดอาหารได้หลายสัปดาห์ แต่ขาดน้ำได้ไม่เกินสามวัน น้ำจึงไม่ใช่เพียงของใช้ประจำวัน แต่เป็นเงื่อนไขของการมีชีวิตอยู่',
      heroImage: 'work-02',
      heroAlt: 'รถส่งน้ำธารนทีกำลังเติมน้ำเข้าแท็งก์เก็บน้ำของลูกค้า',
      heroCaption: 'น้ำประปาส่งตรงถึงแท็งก์เก็บน้ำของลูกค้า ด้วยรถส่งน้ำธารนที',
      tocTitle: 'หัวข้อในหน้านี้',
      groupsTitle: 'ความสำคัญของน้ำต่อสิ่งมีชีวิตและโลก',
      groups: [
        { icon: 'drop', title: 'การดำรงชีวิต', text: 'ร่างกายมนุษย์มีน้ำเป็นส่วนประกอบหลัก น้ำช่วยควบคุมอุณหภูมิ ย่อยอาหาร และลำเลียงสารอาหารไปเลี้ยงทุกส่วนของร่างกาย' },
        { icon: 'leaf', title: 'เกษตรกรรมและอาหาร', text: 'น้ำคือหัวใจของการเพาะปลูกและการเลี้ยงสัตว์ ซึ่งเป็นแหล่งอาหารของคนทั้งประเทศ ไม่มีน้ำก็ไม่มีผลผลิต' },
        { icon: 'pool', title: 'ระบบนิเวศ', text: 'แหล่งน้ำเป็นทั้งจุดกำเนิดและที่อยู่อาศัยของสัตว์น้ำและสิ่งมีชีวิตอีกนับไม่ถ้วน ทำหน้าที่รักษาสมดุลของธรรมชาติ' },
      ],
      usesTitle: 'การใช้น้ำในแต่ละภาคส่วน',
      uses: [
        { image: 'work-04', alt: 'เติมน้ำเข้าแท็งก์หน้าห้องแถว', title: 'อุปโภคในบ้านและร้านค้า', text: 'ประกอบอาหาร ชำระล้างร่างกาย ซักผ้า ล้างจาน ทำความสะอาด และงานบ้านแทบทุกอย่างในชีวิตประจำวัน' },
        { image: 'work-08', alt: 'ใช้น้ำล้างพื้นภายในอาคารโกดัง', title: 'อุตสาหกรรม', text: 'ใช้ในกระบวนการผลิต หล่อเย็นเครื่องจักร และล้างทำความสะอาดภายในโรงงาน' },
        { image: 'work-09', alt: 'รถส่งน้ำจอดส่งน้ำใต้ร่มไม้ในสวน', title: 'เกษตรและปศุสัตว์', text: 'รดน้ำแปลงเพาะปลูก ให้สัตว์กิน อาบน้ำให้สัตว์ และฉีดพรมคอกให้เย็นชุ่มชื้นในหน้าแล้ง' },
      ],
      benefitsTitle: 'ความสำคัญของน้ำประปา',
      benefitsSubtitle: 'เจ็ดเหตุผลที่ระบบน้ำประปาสะอาดเปลี่ยนคุณภาพชีวิตของคนทั้งชุมชน',
      benefitsImage: 'work-05',
      benefitsAlt: 'แท็งก์เก็บน้ำสีน้ำเงินสองใบข้างอาคาร',
      benefitsCaption: 'แท็งก์สำรองน้ำช่วยให้มีน้ำใช้ต่อเนื่อง แม้ในช่วงหน้าแล้งที่น้ำประปาไหลไม่พอ',
      benefits: [
        { title: 'มีน้ำพอใช้ตลอดทั้งปี', text: 'ระบบประปาจ่ายน้ำได้สม่ำเสมอ ทำให้มีน้ำเพียงพอต่อการดำรงชีวิต โดยเฉพาะช่วงหน้าแล้งที่น้ำมักไม่พอกับความต้องการ' },
        { title: 'มีน้ำสำหรับงานอุปโภค', text: 'ล้างรถ ล้างจาน ซักผ้า รดน้ำต้นไม้ ทำความสะอาดบ้านและร้านค้า ล้วนต้องใช้น้ำที่ไหลได้ตลอดเวลา' },
        { title: 'น้ำสำหรับดื่มต้องต้มหรือกรองก่อน', text: 'น้ำประปาเป็นต้นทางของน้ำดื่มในหลายบ้าน แต่น้ำที่พักในแท็งก์หรือขนส่งมาทางรถอาจมีตะกอนปน ก่อนนำไปดื่มหรือประกอบอาหารจึงควรต้มหรือผ่านเครื่องกรองทุกครั้ง น้ำที่ธารนทีจัดส่งเป็นน้ำประปาสำหรับงานอุปโภค ไม่ได้จำหน่ายเป็นน้ำดื่ม' },
        { title: 'มีน้ำสำหรับการเกษตร', text: 'แปลงเพาะปลูกขนาดเล็กและสวนครัวใช้น้ำประปาได้สะดวก ส่วนแปลงขนาดใหญ่ควรมีแหล่งน้ำสำรอง เพราะหน้าร้อนน้ำประปาอาจไม่พอสำหรับทั้งหมู่บ้าน' },
        { title: 'มีน้ำสำหรับโรงงานอุตสาหกรรม', text: 'โรงงานต้องใช้น้ำปริมาณมากและต้องสะอาดพอที่จะเข้าสู่กระบวนการผลิต ระบบน้ำของโรงงานจึงต้องวางแผนอย่างพิถีพิถัน' },
        { title: 'มีน้ำสำหรับปศุสัตว์', text: 'สัตว์เลี้ยงต้องกินน้ำทุกวัน ยิ่งหน้าแล้งที่สระและคลองแห้งลง น้ำประปายิ่งจำเป็น ทั้งสำหรับให้กิน อาบ และฉีดพรมคอกให้เย็น' },
        { title: 'มีน้ำใช้ทั่วถึงทั้งชุมชน', text: 'เมื่อหมู่บ้านมีระบบประปา น้ำจะถูกจ่ายไปถึงทุกหลังคาเรือนอย่างเท่าเทียม ไม่ใช่เฉพาะบ้านที่อยู่ใกล้แหล่งน้ำเท่านั้น' },
      ],
      summaryTitle: 'สรุปเรื่องความสำคัญของน้ำประปา',
      summaryImage: 'work-06',
      summaryAlt: 'พนักงานธารนทีฉีดน้ำล้างถนนในเวลากลางคืน',
      summaryCaption: 'ธารนทีให้บริการตลอด 24 ชั่วโมง รวมถึงงานล้างถนนในเวลากลางคืน',
      summaryText: 'น้ำประปาที่สะอาดและมีให้ใช้อย่างสม่ำเสมอ คือพื้นฐานของคุณภาพชีวิตทั้งของคนและสัตว์ เมื่อใดที่น้ำในระบบไม่พอ ไม่ว่าจะเป็นหน้าแล้ง ท่อประปาซ่อม หรือพื้นที่ที่ท่อยังไปไม่ถึง การมีรถส่งน้ำที่เรียกได้ทันทีจะช่วยให้บ้าน ร้านค้า และไซต์งานเดินต่อไปได้โดยไม่ต้องหยุดรอ',
      ctaTitle: 'ต้องการน้ำประปาส่งถึงที่',
      ctaText: 'ธารนที รถส่งน้ำประปาเชียงใหม่และลำพูน บริการตลอด 24 ชั่วโมง โทรหาเราได้ทุกเวลา',
      backLabel: 'กลับไปหน้าแรก',
    },

    videos: [
      { file: 'work-video-01', poster: '', caption: 'เติมน้ำให้ร้านค้าและคาเฟ่' },
      { file: 'work-video-02', poster: '', caption: 'เติมแท็งก์น้ำบ้านพักอาศัย' },
      { file: 'work-video-03', poster: '', caption: 'ส่งถึงหน้าบ้าน เข้าซอยแคบได้' },
      { file: 'work-video-04', poster: '', caption: 'ส่งน้ำให้คลินิกและสำนักงาน' },
    ],

    galleryTitle: 'ผลงานของเรา',
    gallerySubtitle: 'ตัวอย่างงานจัดส่งน้ำประปาที่ผ่านมา ทั้งงานอีเวนต์ ร้านอาหาร โรงแรม ไซต์ก่อสร้าง และงานล้างสถานที่',
    galleryAlt: 'ผลงานรถส่งน้ำประปาเชียงใหม่',
    galleryOpen: 'ดูรูปผลงานขนาดเต็ม',
    videoPlay: 'เล่นคลิป',
    viewerLabel: 'ตัวดูผลงาน รูปและคลิป',
    viewerClose: 'ปิด',
    viewerPrev: 'ก่อนหน้า',
    viewerNext: 'ถัดไป',
    viewerOf: 'จาก',
    viewerHint: 'ปัดซ้ายขวาเพื่อดูรายการอื่น',

    faqTitle: 'คำถามที่พบบ่อย',
    faq: [
      { q: 'สั่งน้ำแล้วรอนานไหม', a: 'ขึ้นอยู่กับคิวรถและระยะทาง โดยทั่วไปในเขตอำเภอเมืองจัดส่งได้ภายในวันเดียวกัน กรณีเร่งด่วนแจ้งได้ตอนโทร ทีมงานจะจัดคิวให้ก่อน' },
      { q: 'น้ำที่ส่งเป็นน้ำอะไร ใช้ดื่มได้หรือไม่', a: 'เป็นน้ำประปาสำหรับงานอุปโภค ไม่ได้จำหน่ายเป็นน้ำดื่ม กรุณาแจ้งลักษณะการใช้งานและสอบถามรายละเอียดก่อนสั่ง' },
      { q: 'คิดค่าบริการอย่างไร', a: 'คิดตามปริมาณน้ำและระยะทางจากจุดรับน้ำถึงหน้างาน แจ้งราคาทั้งหมดให้ทราบก่อนออกรถ ไม่มีค่าใช้จ่ายเพิ่มหน้างาน' },
      { q: 'รถเข้าซอยแคบได้ไหม', a: 'ได้ กรณีซอยแคบหรือทางเข้าจำกัดจะใช้รถ 4 ล้อแทนรถ 6 ล้อ แจ้งลักษณะทางเข้าตอนสั่งน้ำเพื่อให้จัดรถได้ถูกประเภท' },
      { q: 'รับส่งน้ำนอกเขตเชียงใหม่และลำพูนหรือไม่', a: 'รับพิจารณาเป็นกรณีไป ขึ้นอยู่กับระยะทางและปริมาณน้ำ โทรสอบถามเพื่อประเมินราคาได้' },
      { q: 'ชำระเงินอย่างไร', a: 'ชำระเงินสดหน้างานหรือโอนผ่านธนาคาร กรณีลูกค้าองค์กรที่ต้องการวางบิลแจ้งล่วงหน้าได้' },
      { q: 'อยากซื้อน้ำ สั่งรถน้ำในเชียงใหม่ ต้องทำอย่างไร', a: 'โทรหรือทักไลน์ แจ้งปริมาณน้ำ สถานที่ และเวลาที่ต้องการ ทีมงานแจ้งราคาและยืนยันคิวรถ จากนั้นรถขายน้ำจะนำน้ำไปเติมให้ถึงหน้างาน' },
      { q: 'หารถน้ำ รถส่งน้ำใกล้ฉัน ธารนทีไปส่งถึงไหม', a: 'รถส่งน้ำของเราให้บริการทั่วเชียงใหม่และลำพูน ส่งตำแหน่งหรือพิกัดทางไลน์ ทีมงานจะแจ้งเวลาที่รถไปถึงโดยประมาณก่อนออกรถ' },
      { q: 'มีรถน้ำสำหรับงานสงกรานต์ไหม', a: 'มี รับจัดรถน้ำสำหรับงานสงกรานต์ งานวัด งานเทศกาล และงานอีเวนต์ แนะนำให้จองล่วงหน้าเพื่อจัดคิวรถได้ตรงเวลาที่ต้องการ' },
    ],

    ctaTitle: 'ต้องการน้ำด่วนวันนี้',
    ctaSubtitle: 'โทรหาเราได้ตลอด 24 ชั่วโมง ทีมงานพร้อมจัดรถให้ทันที',

    formHeading: 'ให้ทีมงานติดต่อกลับ',
    formSubject: 'ลูกค้าสั่งน้ำผ่านเว็บไซต์',
    formName: 'ชื่อผู้ติดต่อ',
    formPhone: 'เบอร์โทรกลับ',
    formPhoneHint: 'กรอกเฉพาะตัวเลข เช่น 0812345678',
    formArea: 'พื้นที่จัดส่ง',
    formAreaPlaceholder: 'เช่น อำเภอสันทราย',
    formMessage: 'รายละเอียด',
    formMessagePlaceholder: 'ปริมาณน้ำที่ต้องการ วันและเวลาที่สะดวกรับน้ำ',
    formRequired: 'จำเป็น',
    formTrap: 'เว้นช่องนี้ว่างไว้',
    formSubmit: 'ส่งข้อมูลให้ทีมงานติดต่อกลับ',
    formSending: 'กำลังส่ง',
    formSent: 'ส่งข้อความเรียบร้อยแล้ว ทีมงานจะติดต่อกลับโดยเร็วที่สุด หากเร่งด่วนกรุณาโทรหาเราโดยตรง',
    formError: 'ส่งข้อความไม่สำเร็จ กรุณาโทรหาเราโดยตรงเพื่อความรวดเร็ว',
    formHint: 'ใช้ข้อมูลนี้เพื่อติดต่อกลับเรื่องบริการ เก็บในระบบของร้าน 90 วัน หากต้องการน้ำด่วนวันนี้ กรุณาโทรโดยตรง',
    reviewsLabel: 'รีวิวบน Google',

    contactTitle: 'ติดต่อสั่งน้ำ',
    contactSubtitle: 'โทรได้เลยเพื่อความรวดเร็วที่สุด หรือทักไลน์เพื่อส่งรายละเอียดงานให้ทีมงาน',
    labelPhone: 'โทรศัพท์',
    labelLine: 'LINE',
    labelFacebook: 'Facebook',
    labelPage: 'เพจ',
    labelEmail: 'อีเมล',
    labelLocation: 'พื้นที่ตั้ง',
    labelHours: 'เวลาให้บริการ',
    mapLink: 'เปิดเส้นทางใน Google Maps',
    mapTitle: 'แผนที่',
    copyPhone: 'คัดลอก',
    copyError: 'คัดลอกไม่ได้ กรุณาจดเบอร์นี้',
    copied: 'คัดลอกเบอร์แล้ว',

    footerContact: 'ติดต่อเรา',
    footerAreas: 'พื้นที่ให้บริการ',
    footerRights: 'สงวนลิขสิทธิ์',
    footerNote: 'TN Water Truck Services',
  },

  en: {
    lang: 'en',
    siteName: 'Natee',
    tagline: 'Water truck delivery in Chiang Mai, open 24 hours',
    address: '100/29 Moo 3, San Phi Suea, Mueang Chiang Mai, Chiang Mai 50300',
    hours: 'Open every day, 24 hours',

    nav: {
      services: 'Services',
      fleet: 'Our trucks',
      pricing: 'Pricing',
      areas: 'Service areas',
      gallery: 'Our work',
      faq: 'FAQ',
      contact: 'Contact',
    },

    skipToContent: 'Skip to main content',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    mainMenu: 'Main menu',
    changeLanguage: 'Change language',
    callLabel: 'Call to order',
    callHeader: 'Call us 24 hours',
    lineLabel: 'Chat on LINE',
    orCall: 'or call',

    heroEyebrow: 'Fast, on time, and we care about every job',
    heroTitle: 'Water truck delivery in Chiang Mai and Lamphun, 24 hours a day',
    heroSubtitle: 'Clean tap water delivered to storage tanks, swimming pools, construction sites, gardens and lawns, road washing, festivals and events. We deliver anywhere in Chiang Mai and Lamphun.',
    heroNote: 'Tell us how much water you need, where, and when. We quote you straight away.',

    highlightsTitle: 'Why customers choose us',
    highlights: [
      { icon: 'clock', title: 'We move fast', text: 'Water cannot wait. The moment you call, we arrange a truck and get moving.' },
      { icon: 'check', title: 'On time, every time', text: 'No worrying about the appointment. We arrive at the time we agreed with you.' },
      { icon: 'drop', title: 'Water for non-drinking uses', text: 'Tap-water delivery for tank filling and other non-drinking uses. Tell us your intended use and ask for details before ordering.' },
      { icon: 'truck', title: 'We reach every site', text: 'With both four wheel and six wheel trucks we can deliver anywhere in Chiang Mai, Lamphun and nearby provinces.' },
    ],

    aboutTitle: 'Clean water you can rely on, delivered by Natee',
    aboutText: 'Natee started with one goal: to bring clean, good quality tap water to people across Chiang Mai and Lamphun. We serve homes, shops, businesses, construction sites, places that need backup water when the mains run short, swimming pools, special events, and areas the pipe network has not reached. We work with care, responsibility and proper standards.',
    aboutQuote: 'Water is life. Without water, people cannot live.',

    servicesTitle: 'What we deliver',
    servicesSubtitle: 'Water delivery for every kind of job, urgent or scheduled, around the clock.',
    services: [
      { icon: 'tank', title: 'Filling water storage tanks', text: 'When the mains stop, a pipe bursts, or the network does not reach you, we fill your tank so you can carry on. Homes, dormitories, condominiums and offices.' },
      { icon: 'pool', title: 'Filling swimming pools', text: 'Pools at homes, hotels, resorts and condominiums, plus fountains and fish ponds, filled with clean tap water.' },
      { icon: 'build', title: 'Construction sites', text: 'Water by the load or by the day for mixing concrete, compacting ground, and daily use in the workers camp.' },
      { icon: 'leaf', title: 'Watering gardens and lawns', text: 'Gardens, lawns, trees in housing projects and farm land, especially through the dry season when water runs short.' },
      { icon: 'road', title: 'Water spray truck for roads and buildings', text: 'Roads, car parks, buildings and dusty or muddy work sites washed down and ready to use again.' },
      { icon: 'event', title: 'Songkran and events', text: 'Water trucks for Songkran, concerts, events and festivals. We can plan the delivery schedule with you in advance.' },
      { icon: 'factory', title: 'Factories and industry', text: 'Large volumes for factories and industrial premises, delivered on a schedule we agree with you.' },
      { icon: 'hotel', title: 'Hotels, restaurants and cafes', text: 'Daily deliveries for hospitality businesses so you never run dry in the middle of service.' },
    ],

    fleetTitle: 'Our water trucks',
    fleetSubtitle: 'Choose the truck that suits the volume of water and the access to your site.',
    fleet: [
      { image: 'truck-6wheel', name: 'Six wheel water truck', capacity: 'Large capacity', text: 'Best for factories, condominiums, swimming pools, hotels and construction projects that need a lot of water in one trip. Good value and saves time.' },
      { image: 'truck-4wheel', name: 'Four wheel water truck', capacity: 'Compact, fits narrow lanes', text: 'Best for houses, townhomes and sites down narrow lanes where a big truck cannot go. Easy access, easy parking, no blocked traffic.' },
    ],

    pricingTitle: 'Service rates',
    pricingSubtitle: 'The price depends on the volume of water, the distance and the time of delivery. Call us for an exact quote.',
    pricing: [
      {
        name: 'Four wheel truck',
        detail: 'For homes and narrow lanes',
        price: 'Ask for a quote',
        includes: ['Fits narrow lanes and tight parking', 'Ideal for topping up home and dormitory tanks', 'We confirm the price before the truck leaves'],
      },
      {
        name: 'Six wheel truck',
        detail: 'For sites, factories and pools',
        price: 'Ask for a quote',
        includes: ['A large volume delivered in a single trip', 'Suits construction sites, factories and pool filling', 'Delivery rounds can be planned in advance'],
      },
      {
        name: 'Monthly contract',
        detail: 'A fixed schedule at a special rate',
        price: 'Ask for a quote',
        includes: ['Set the days and times that suit you', 'Special rates for regular customers', 'Invoicing available for business customers'],
      },
    ],
    pricingNote: 'These are starting rates. Areas outside Mueang Chiang Mai and urgent out of hours jobs may cost more. We always tell you the price before the truck leaves.',
    priceCallNow: 'Call for a quote',

    stepsTitle: 'Ordering takes three steps',
    steps: [
      { title: 'Call or message us on LINE', text: 'Tell us how much water you need, where to deliver it, and when suits you.' },
      { title: 'Get the price and confirm', text: 'We work out the distance and quote you straight away. Once you confirm, we book the truck.' },
      { title: 'We deliver to your door', text: 'Our driver fills exactly where you need it. We check the volume together before you pay.' },
    ],

    areasTitle: 'Where we deliver',
    areasSubtitle: 'We serve the whole of Chiang Mai and Lamphun provinces, plus the areas nearby. Ask us about anywhere else.',
    areas: [
      'Mueang Chiang Mai', 'San Sai', 'Saraphi', 'Hang Dong',
      'San Kamphaeng', 'Doi Saket', 'Mae Rim', 'Lamphun province',
      'San Pa Tong', 'Mae Taeng', 'Samoeng', 'Chom Thong', 'Mae On',
    ],

    servicePages: [
      {
        slug: 'tank-filling',
        icon: 'tank',
        navLabel: 'Tank filling',
        metaTitle: 'Water Tank Filling in Chiang Mai, Buy Water 24 Hours | Natee',
        metaDescription: 'No water, a burst pipe or low pressure? Buy water from Natee. Our water trucks fill tanks at homes, dormitories, condos and shops across Chiang Mai and Lamphun.',
        eyebrow: 'Tank filling',
        title: 'Water truck tank filling in Chiang Mai',
        subtitle: 'When the mains stop or a pipe bursts, order a Natee water truck to fill your tank so you can carry on.',
        image: 'work-05',
        imageAlt: 'A blue water storage tank being filled from a Natee delivery hose',
        imageCaption: 'Filling a customer storage tank',
        intro: 'When the mains stop, a pipe bursts or the pressure is too low, daily life gets hard. Natee has water trucks ready 24 hours a day to fill storage tanks at homes, dormitories, condominiums, offices and shops across Chiang Mai and Lamphun.',
        fitTitle: 'When to call us',
        fits: ['Homes where the mains run dry or weak in the dry season', 'Dormitories, condos and apartments with shared tanks', 'Shops, restaurants and cafes that run out of water during service', 'Homes and land the pipe network has not reached', 'Pipe repairs that shut the water off for hours'],
        tipsTitle: 'Before you order',
        tips: ['Check the tank size or the amount of water you need and tell us when you call', 'Describe the entrance. For narrow lanes we send the four wheel truck', 'Send your location on LINE so the driver finds you first time', 'We deliver tap water for non-drinking use. It is not sold as drinking water'],
        faq: [
          { q: 'How is tank filling priced?', a: 'By the volume of water and the distance from where we load to your site. We tell you the full price before the truck leaves, with nothing added on arrival.' },
          { q: 'Can I order at night?', a: 'Yes. Natee takes orders 24 hours a day, every day. Call or message us on LINE any time.' },
          { q: 'Can I drink the water?', a: 'It is tap water for non-drinking uses such as bathing and cleaning. It is not sold as drinking water.' },
        ],
      },
      {
        slug: 'pool-filling',
        icon: 'pool',
        navLabel: 'Swimming pool filling',
        metaTitle: 'Swimming Pool Filling Water Truck, Chiang Mai | Natee',
        metaDescription: 'Water trucks to fill swimming pools, fountains and fish ponds at homes, hotels, resorts and condos in Chiang Mai and Lamphun. Tell us the pool size for a quote.',
        eyebrow: 'Pool filling',
        title: 'Swimming pool filling in Chiang Mai',
        subtitle: 'New pools, refills after cleaning, or topping up in the hot season. Tap water delivered to the edge of your pool.',
        image: 'work-11',
        imageAlt: 'A Natee water truck running a delivery hose into a house',
        imageCaption: 'Running a hose from the truck into a home',
        intro: 'Filling a pool from a garden tap takes a long time and drains the water you need in the house. Natee delivers tap water by truck and fills your pool straight from the hose, for homes, hotels, resorts and condominiums, as well as fountains and fish ponds in Chiang Mai and Lamphun.',
        fitTitle: 'When to call us',
        fits: ['A newly built pool that needs its first fill', 'A pool drained for cleaning or repair', 'Hotel and resort pools that need topping up in the hot season', 'Fountains, fish ponds and garden ponds'],
        tipsTitle: 'Before you order',
        tips: ['Tell us the length, width and rough depth of the pool and we will work out the number of loads', 'Tell us the distance from where the truck can park to the pool edge', 'If it must be done in one day, book ahead so we can schedule several loads back to back'],
        faq: [
          { q: 'How many loads does a pool need?', a: 'It depends on the pool size and the truck size. Give us the length, width and depth and we will work out the volume and number of loads before confirming the price.' },
          { q: 'What if the truck cannot reach the pool?', a: 'We run a delivery hose from the truck to the pool. Tell us the distance when you order so we bring enough hose.' },
          { q: 'Do you fill fish ponds and fountains?', a: 'Yes, with the same tap water. Tell us the size so we can estimate the volume.' },
        ],
      },
      {
        slug: 'songkran',
        icon: 'event',
        navLabel: 'Songkran and events',
        metaTitle: 'Songkran Water Truck in Chiang Mai, Events and Festivals | Natee',
        metaDescription: 'Book a water truck for Songkran, temple fairs, festivals, concerts and events in Chiang Mai and Lamphun. We plan refill rounds with you before the day.',
        eyebrow: 'Festivals and events',
        title: 'Songkran and event water trucks in Chiang Mai',
        subtitle: 'Backup water for Songkran, temple fairs, concerts and festivals. Book ahead to secure a truck for your time slot.',
        image: 'work-01',
        imageAlt: 'A Natee water truck serving a night festival',
        imageCaption: 'Delivering water to a night festival',
        intro: 'Songkran and festivals use a lot of water in a short time, and running dry halfway through hurts both organisers and guests. Natee supplies water trucks for Songkran, temple fairs, concerts and events, and plans the refill rounds with organisers before the day.',
        fitTitle: 'When to call us',
        fits: ['Community, village, shop and company Songkran events', 'Temple fairs, traditional ceremonies and annual festivals', 'Concerts, events and markets that need backup water', 'Refilling tanks and containers set up on site'],
        tipsTitle: 'Before you book',
        tips: ['Book early so we can schedule a truck for your date and time', 'Tell us the date, time and how many refills you need during the event', 'Send a site plan or the parking point so the truck can get in and out easily'],
        faq: [
          { q: 'How early should I book a Songkran water truck?', a: 'The earlier the better, especially at Songkran when many events run at once. Call or message us on LINE with your date to hold a truck.' },
          { q: 'Can you refill several times during the event?', a: 'Yes. We plan the refill rounds with you in advance. Tell us when you need each refill.' },
          { q: 'Do you work outside Mueang Chiang Mai?', a: 'We cover all of Chiang Mai and Lamphun. For other areas, ask us for a quote based on the distance.' },
        ],
      },
      {
        slug: 'road-washing',
        icon: 'road',
        navLabel: 'Road washing',
        metaTitle: 'Road Washing Water Truck, Chiang Mai and Lamphun | Natee',
        metaDescription: 'Water spray trucks to wash roads, car parks, buildings and muddy sites after construction or flooding in Chiang Mai and Lamphun, 24 hours a day.',
        eyebrow: 'Washing and cleaning',
        title: 'Road and building washing in Chiang Mai',
        subtitle: 'Roads, car parks and dusty or muddy areas washed down and ready to use again.',
        image: 'work-06',
        imageAlt: 'A Natee crew washing a road with a hose at night',
        imageCaption: 'Washing a road at night',
        intro: 'Roads outside projects, car parks and areas after construction build up dust and mud. Natee has water trucks with spray hoses for washing down large areas, day or night, so the space is clean and usable again.',
        fitTitle: 'When to call us',
        fits: ['Roads outside construction sites with mud tracked by vehicles', 'Car parks, event grounds and building forecourts', 'Areas left muddy after a flood', 'Cleaning a site before or after an event'],
        tipsTitle: 'Before you order',
        tips: ['Tell us the size of the area and how dirty it is so we can estimate the water', 'For public roads, choose a time that does not block traffic', 'Show us the drains so the wash water can run off'],
        faq: [
          { q: 'Can you wash roads at night?', a: 'Yes. Natee works 24 hours a day, and night time often suits road washing when traffic is light.' },
          { q: 'How is road washing priced?', a: 'By the volume of water used and the distance to the site. Tell us the size of the area and we will quote before the truck leaves.' },
          { q: 'Do you wash building floors or warehouses?', a: 'Yes. Tell us the floor area and where the drains are and we will assess the job first.' },
        ],
      },
      {
        slug: 'garden-watering',
        icon: 'leaf',
        navLabel: 'Garden and lawn watering',
        metaTitle: 'Garden and Lawn Watering Truck in Chiang Mai | Natee',
        metaDescription: 'Water trucks for watering gardens, lawns, trees in housing projects and farm land through the dry season in Chiang Mai and Lamphun, one off or on a schedule.',
        eyebrow: 'Watering',
        title: 'Garden and lawn watering in Chiang Mai',
        subtitle: 'Water for gardens, lawns and trees in housing projects when the dry season leaves you short.',
        image: 'work-09',
        imageAlt: 'A Natee water truck parked beside a line of trees',
        imageCaption: 'Delivering water to a customer garden',
        intro: 'In the Chiang Mai dry season there is often not enough water for large gardens and lawns. Natee delivers tap water by truck for gardens, lawns, trees in housing projects, resorts and farm land, as a one off job or on a schedule we agree with you.',
        fitTitle: 'When to call us',
        fits: ['Lawns and gardens at homes, resorts and hotels', 'Trees in housing estates and shared areas', 'Newly planted trees on construction projects', 'Farm plots and orchards short of water'],
        tipsTitle: 'Before you order',
        tips: ['Tell us the size of the area and how many times a week you need water', 'For a regular schedule, agree the days and times with us in advance', 'Show us where the truck can park and how far it is to the garden'],
        faq: [
          { q: 'Can you water every week?', a: 'Yes. We can agree regular delivery rounds, which suits the dry season when watering must continue.' },
          { q: 'How much water does a lawn need?', a: 'It depends on the area and the weather. Tell us the size of the lawn and we will help estimate the volume.' },
          { q: 'What water do you use?', a: 'Tap water, delivered directly from Natee water trucks.' },
        ],
      },
    ],
    serviceMore: 'See service details',
    serviceRelated: 'Other Natee services',
    serviceFaqTitle: 'Questions about this service',
    serviceBack: 'Back to the home page',

    knowledge: {
      navLabel: 'Water facts',
      metaTitle: 'Why Water and Tap Water Matter | Natee',
      metaDescription: 'Why water and a clean tap water supply matter for daily life, farming, livestock, industry and communities, from the Natee water truck team in Chiang Mai.',
      eyebrow: 'Good to know',
      title: 'Water is life: why water and tap water matter',
      subtitle: 'What is worth knowing about water and a piped water supply, from everyday household use to farming, livestock, industry, and getting water to every home in a village.',
      quote: 'Water is life. Without water, people cannot live.',
      quoteBy: 'His Majesty King Bhumibol Adulyadej the Great',
      intro: 'Water is the most basic requirement of every living thing on earth. A person can go weeks without food, but no more than three days without water. Water is not simply another household supply, it is the condition for staying alive.',
      heroImage: 'work-02',
      heroAlt: 'A Natee water truck filling a customer storage tank',
      heroCaption: 'Tap water delivered straight into a customer storage tank by a Natee truck',
      tocTitle: 'On this page',
      groupsTitle: 'Why water matters to life and to the planet',
      groups: [
        { icon: 'drop', title: 'Staying alive', text: 'The human body is mostly water. It regulates temperature, digests food, and carries nutrients to every part of the body.' },
        { icon: 'leaf', title: 'Farming and food', text: 'Water is at the heart of growing crops and raising animals, which feed the whole country. No water means no harvest.' },
        { icon: 'pool', title: 'Ecosystems', text: 'Rivers, lakes and ponds are where aquatic life begins and lives. They hold the balance of the natural world together.' },
      ],
      usesTitle: 'How each sector uses water',
      uses: [
        { image: 'work-04', alt: 'Filling storage tanks in front of a shophouse', title: 'Homes and shops', text: 'Cooking, washing, laundry, dishes, cleaning, and almost every other daily task at home and in the shop.' },
        { image: 'work-08', alt: 'Washing down a warehouse floor with water', title: 'Industry', text: 'Production processes, cooling machinery, and cleaning inside the plant.' },
        { image: 'work-09', alt: 'A water truck delivering to a garden under the trees', title: 'Farming and livestock', text: 'Watering crops, drinking water for animals, washing them, and damping down pens to keep them cool in the dry season.' },
      ],
      benefitsTitle: 'Why a piped water supply matters',
      benefitsSubtitle: 'Seven reasons a clean tap water supply changes daily life for a whole community',
      benefitsImage: 'work-05',
      benefitsAlt: 'Two blue water storage tanks beside a building',
      benefitsCaption: 'Storage tanks keep water on hand through the dry season, when the mains cannot keep up',
      benefits: [
        { title: 'Enough water all year round', text: 'A piped supply delivers water steadily, so there is enough for daily life even in the dry season when demand outstrips what is available.' },
        { title: 'Water for household chores', text: 'Washing the car, the dishes and the laundry, watering plants, cleaning the house and the shop all need water that runs on demand.' },
        { title: 'Boil or filter before drinking', text: 'Tap water is where drinking water starts for many homes, but water stored in a tank or carried by truck can pick up sediment. Always boil or filter it before drinking or cooking. The tap water Natee delivers is for non-drinking uses and is not sold as drinking water.' },
        { title: 'Water for farming', text: 'Small plots and kitchen gardens can rely on tap water. Larger fields should keep their own reserve, because in hot weather the mains may not cover a whole village.' },
        { title: 'Water for factories', text: 'Plants use large volumes, and it has to be clean enough to enter the production line, so an industrial water system needs careful planning.' },
        { title: 'Water for livestock', text: 'Animals drink every day. In the dry season, when ponds and canals run low, tap water becomes essential for drinking, washing and cooling the pens.' },
        { title: 'Water that reaches the whole village', text: 'Once a village has a piped supply, water reaches every household equally, not only the homes closest to the source.' },
      ],
      summaryTitle: 'In summary',
      summaryImage: 'work-06',
      summaryAlt: 'A Natee crew washing a road at night',
      summaryCaption: 'Natee works around the clock, including night-time road washing',
      summaryText: 'A clean, reliable water supply is the foundation of a decent life for people and animals alike. Whenever the mains fall short, in a drought, during pipe repairs, or in places the network has not reached, a water truck you can call straight away keeps homes, shops and work sites running instead of waiting.',
      ctaTitle: 'Need water delivered to your door',
      ctaText: 'Natee delivers tap water by truck across Chiang Mai and Lamphun, 24 hours a day. Call us any time.',
      backLabel: 'Back to the home page',
    },

    videos: [
      { file: 'work-video-01', poster: '', caption: 'Filling tanks for shops and cafes' },
      { file: 'work-video-02', poster: '', caption: 'Filling a home water tank' },
      { file: 'work-video-03', poster: '', caption: 'Delivered to your door, even down narrow lanes' },
      { file: 'work-video-04', poster: '', caption: 'Delivering to clinics and businesses' },
    ],

    galleryTitle: 'Our work',
    gallerySubtitle: 'Recent deliveries for events, restaurants, hotels, construction sites and site cleaning.',
    galleryAlt: 'Water delivery work by',
    galleryOpen: 'View the full size photo',
    videoPlay: 'Play the clip',
    viewerLabel: 'Work viewer, photos and clips',
    viewerClose: 'Close',
    viewerPrev: 'Previous',
    viewerNext: 'Next',
    viewerOf: 'of',
    viewerHint: 'Swipe left or right to see more',

    faqTitle: 'Frequently asked questions',
    faq: [
      { q: 'How long is the wait after I order?', a: 'It depends on the queue and the distance. Inside Mueang Chiang Mai we can usually deliver the same day. Tell us when you call if it is urgent and we will move you up the queue.' },
      { q: 'What kind of water is it? Can I drink it?', a: 'We deliver tap water for non-drinking uses. It is not sold as drinking water. Tell us your intended use and ask for details before ordering.' },
      { q: 'How is the price worked out?', a: 'By the volume of water and the distance from where we load to your site. We tell you the full price before the truck leaves, with nothing added on arrival.' },
      { q: 'Can your truck get down a narrow lane?', a: 'Yes. Where access is tight we send the four wheel truck instead of the six wheel. Describe the entrance when you order so we send the right vehicle.' },
      { q: 'Do you deliver outside Chiang Mai and Lamphun?', a: 'We consider it case by case, depending on the distance and the volume. Call us and we will work out a price.' },
      { q: 'How do I pay?', a: 'Cash on delivery or bank transfer. Business customers who need an invoice can arrange it with us in advance.' },
      { q: 'How do I order a water truck in Chiang Mai?', a: 'Call or message us on LINE with the amount of water, the location and the time you need it. We confirm the price and the truck, then deliver and fill on site.' },
      { q: 'Is there a water truck near me?', a: 'Our trucks cover the whole of Chiang Mai and Lamphun. Send your location on LINE and we will tell you roughly when the truck can arrive before it leaves.' },
      { q: 'Do you provide water trucks for Songkran?', a: 'Yes. We supply water trucks for Songkran, temple fairs, festivals and events. Book ahead so we can schedule a truck for the time you need.' },
    ],

    ctaTitle: 'Need water today?',
    ctaSubtitle: 'Call us any time, day or night. We will get a truck to you.',

    formHeading: 'Request a call back',
    formSubject: 'Website enquiry for',
    formName: 'Your name',
    formPhone: 'Phone number',
    formPhoneHint: 'Numbers only, for example 0812345678',
    formArea: 'Delivery area',
    formAreaPlaceholder: 'For example, San Sai district',
    formMessage: 'Details',
    formMessagePlaceholder: 'How much water you need, and when you want it delivered',
    formRequired: 'required',
    formTrap: 'Leave this field empty',
    formSubmit: 'Send my details',
    formSending: 'Sending',
    formSent: 'Thank you. We have received your message and will call you back shortly. For urgent orders please call us directly.',
    formError: 'The message could not be sent. Please call us directly instead.',
    formHint: 'We use these details to respond to your enquiry and keep them for 90 days. Need water today? Please call us directly.',
    reviewsLabel: 'reviews on Google',

    contactTitle: 'Contact us',
    contactSubtitle: 'Call us for the fastest response, or message us on LINE with the details of your job.',
    labelPhone: 'Phone',
    labelLine: 'LINE',
    labelFacebook: 'Facebook',
    labelPage: 'Page',
    labelEmail: 'Email',
    labelLocation: 'Location',
    labelHours: 'Opening hours',
    mapLink: 'Open directions in Google Maps',
    mapTitle: 'Map of',
    copyPhone: 'Copy',
    copyError: 'Copy unavailable. Please use this number:',
    copied: 'Phone number copied',

    footerContact: 'Contact',
    footerAreas: 'Service areas',
    footerRights: 'All rights reserved',
    footerNote: 'TN Water Truck Services',
  },
}
